use crate::{DateTime, EventId, Message, Role, RolledBack, ScheduleId, SessionId, Utc};
use serde::{Deserialize, Serialize};

/// A deduplicated input delivered through the Inbox.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// Sender-assigned ID used to deduplicate repeated deliveries across restarts.
    pub id: EventId,
    /// Destination Session whose Inbox accepts this Event.
    pub session: SessionId,
    /// Producer used to distinguish interactive input from system notices.
    pub source: EventSource,
    /// Content that needs a Session Run.
    pub body: EventBody,
    /// Reception time for display, not Inbox ordering.
    pub received_at: DateTime<Utc>,
}

/// The producer of an Inbox input.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventSource {
    /// Input submitted through the native interface.
    Cli,
    /// Interactive input from a channel connection.
    Channel {
        /// Protocol declared by the channel adapter.
        channel: String,
        /// Account identity within the protocol.
        account: String,
        /// Conversation to which default replies return.
        conversation: String,
        /// Authenticated sender within the protocol.
        sender: String,
    },
    /// Input generated by a durable reminder.
    Scheduler,
    /// Notice generated by automatic plugin recovery.
    Registry,
}

/// Input that requires attention from the agent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventBody {
    /// A failed trial generation and its committed replacement.
    GenerationRolledBack(RolledBack),
    /// A message from the owner.
    UserMessage {
        /// Text supplied by the owner.
        text: String,
    },
    /// A reminder reaching its scheduled time.
    Reminder {
        /// The durable reminder which produced this input.
        schedule: ScheduleId,
        /// Scheduled delivery time in UTC.
        due_at: DateTime<Utc>,
        /// Reminder text copied from its Schedule.
        text: String,
    },
}

impl Event {
    /// The sole mapping from Inbox input to a model message.
    pub fn canonical_message(&self) -> Message {
        match &self.body {
            EventBody::GenerationRolledBack(rollback) => {
                let target = match rollback.to {
                    Some(to) => format!("now using generation {to}"),
                    None => "no generation is active".into(),
                };
                Message::text(
                    Role::User,
                    format!(
                        "[plugin rolled back] {}: generation {} failed ({}: {}); {target}",
                        rollback.plugin,
                        rollback.from,
                        rollback.failure.code,
                        rollback.failure.message,
                    ),
                )
            }

            EventBody::UserMessage { text } => Message::text(Role::User, text),
            EventBody::Reminder { due_at, text, .. } => Message::text(
                Role::User,
                format!("[reminder scheduled for {}] {text}", due_at.to_rfc3339()),
            ),
        }
    }
}
