use crate::{DateTime, EventId, Message, Role, RolledBack, ScheduleId, SessionId, Utc};
use serde::{Deserialize, Serialize};

/// A deduplicated input delivered through the Inbox.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Event {
    /// Sender-assigned ID used to deduplicate repeated deliveries across restarts.
    pub id: EventId,
    /// Destination Session whose Inbox accepts this Event.
    pub session: SessionId,
    /// Producer used to distinguish interactive input from system notices.
    pub source: EventSource,
    /// Content that needs a Session Run.
    pub body: EventBody,
    /// Reception time for display, not Inbox ordering.
    pub received_at: DateTime<Utc>,
}

/// The producer of an Inbox input.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventSource {
    /// Input submitted through the native interface.
    Cli,
    /// Interactive input from a channel connection.
    Channel {
        /// Protocol declared by the channel adapter.
        channel: String,
        /// Account identity within the protocol.
        account: String,
        /// Conversation to which default replies return.
        conversation: String,
        /// Authenticated sender within the protocol.
        sender: String,
    },
    /// Input generated by a durable schedule.
    Scheduler,
    /// Notice generated by automatic plugin recovery.
    Registry,
}

/// Input that requires attention from the agent.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum EventBody {
    /// A failed trial generation and its committed replacement.
    GenerationRolledBack {
        /// Committed recovery facts.
        rollback: RolledBack,
        /// Notice written by the Registry when the rollback committed.
        text: String,
    },
    /// A message from the owner.
    UserMessage {
        /// Text supplied by the owner.
        text: String,
    },
    /// A reminder reaching its scheduled time.
    Reminder {
        /// The Schedule which produced this input.
        schedule: ScheduleId,
        /// Planned time in UTC; this occurrence's identity together with the schedule.
        due_at: DateTime<Utc>,
        /// Earlier missed occurrences omitted when delivering only the latest one.
        skipped: u32,
        /// Reminder text copied from its Schedule.
        text: String,
    },
}

impl Event {
    /// The sole mapping from Inbox input to a model message: the text its producer wrote.
    /// The composer narrates the circumstances, such as arrival and planned times.
    pub fn canonical_message(&self) -> Message {
        let (EventBody::GenerationRolledBack { text, .. }
        | EventBody::UserMessage { text }
        | EventBody::Reminder { text, .. }) = &self.body;
        Message::text(Role::User, text)
    }
}
