use anyhow::{Result, bail};
use std::{fmt::Write, fs};
use wit_parser::{Docs, Resolve, Type, TypeDefKind, WorldKey};

pub fn generate(check: bool) -> Result<()> {
    let mut resolve = Resolve::default();
    let (id, _) = resolve.push_dir("wit")?;
    let package = &resolve.packages[id];
    let mut missing = vec![];
    required(&package.docs, "package", &mut missing);
    let mut out = format!(
        "<!-- Generated by `cargo xtask docs`. Do not edit. -->\n# {}\n\n{}\n\n## Worlds\n",
        package.name,
        body(&package.docs)
    );
    for (name, id) in &package.worlds {
        let world = &resolve.worlds[*id];
        required(&world.docs, &format!("world {name}"), &mut missing);
        writeln!(out, "\n### `{name}`\n\n{}\n", body(&world.docs))?;
        for (direction, items) in [("Imports", &world.imports), ("Exports", &world.exports)] {
            let names = items
                .keys()
                .map(|key| match key {
                    WorldKey::Name(name) => name.clone(),
                    WorldKey::Interface(id) => resolve.interfaces[*id]
                        .name
                        .clone()
                        .unwrap_or_else(|| "anonymous".into()),
                })
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "- {direction}: {names}")?;
        }
    }
    out.push_str("\n## Interfaces\n");
    for (name, id) in &package.interfaces {
        let interface = &resolve.interfaces[*id];
        required(&interface.docs, &format!("interface {name}"), &mut missing);
        writeln!(out, "\n### `{name}`\n\n{}", body(&interface.docs))?;
        for (name, id) in &interface.types {
            append_type(&resolve, name, &resolve.types[*id], &mut out, &mut missing)?;
        }
        for (name, function) in &interface.functions {
            append_function(&resolve, name, function, &mut out, &mut missing)?;
        }
    }
    if !missing.is_empty() {
        bail!("missing WIT documentation:\n{}", missing.join("\n"));
    }
    if check {
        if fs::read_to_string("wit/CONTRACT.md").unwrap_or_default() != out {
            bail!("wit/CONTRACT.md is stale; run cargo xtask docs");
        }
    } else {
        fs::write("wit/CONTRACT.md", out)?;
    }
    Ok(())
}

fn append_type(
    resolve: &Resolve,
    name: &str,
    def: &wit_parser::TypeDef,
    out: &mut String,
    missing: &mut Vec<String>,
) -> Result<()> {
    // A WIT `use` refers to the defining interface; it does not need a duplicate doc block.
    if let TypeDefKind::Type(Type::Id(target)) = &def.kind
        && def.owner != resolve.types[*target].owner
    {
        return Ok(());
    }
    required(&def.docs, &format!("type {name}"), missing);
    writeln!(
        out,
        "\n#### {} `{name}`\n\n{}\n",
        def.kind.as_str(),
        body(&def.docs)
    )?;
    match &def.kind {
        TypeDefKind::Record(record) => {
            out.push_str("| Field | Type | Description |\n|---|---|---|\n");
            for field in &record.fields {
                writeln!(
                    out,
                    "| `{}` | `{}` | {} |",
                    field.name,
                    type_name(resolve, field.ty)?,
                    cell(&field.docs)
                )?;
            }
        }
        TypeDefKind::Variant(variant) => {
            out.push_str("| Case | Type | Description |\n|---|---|---|\n");
            for case in &variant.cases {
                writeln!(
                    out,
                    "| `{}` | `{}` | {} |",
                    case.name,
                    optional_type(resolve, case.ty)?,
                    cell(&case.docs)
                )?;
            }
        }
        TypeDefKind::Enum(en) => {
            for case in &en.cases {
                writeln!(
                    out,
                    "- `{}`{}",
                    case.name,
                    if body(&case.docs).is_empty() {
                        String::new()
                    } else {
                        format!(": {}", body(&case.docs))
                    }
                )?;
            }
        }
        kind => {
            writeln!(
                out,
                "```wit\ntype {name} = {};\n```",
                kind_text(resolve, kind)?
            )?;
        }
    }
    Ok(())
}

fn append_function(
    resolve: &Resolve,
    name: &str,
    function: &wit_parser::Function,
    out: &mut String,
    missing: &mut Vec<String>,
) -> Result<()> {
    required(&function.docs, &format!("function {name}"), missing);
    let params = function
        .params
        .iter()
        .map(|p| Ok(format!("{}: {}", p.name, type_name(resolve, p.ty)?)))
        .collect::<Result<Vec<_>>>()?
        .join(", ");
    let result = function
        .result
        .map(|t| type_name(resolve, t).map(|t| format!(" -> {t}")))
        .transpose()?
        .unwrap_or_default();
    writeln!(
        out,
        "\n#### func `{name}`\n\n```wit\n{name}: {}func({params}){result};\n```\n\n{}",
        if function.kind.is_async() {
            "async "
        } else {
            ""
        },
        body(&function.docs)
    )?;
    Ok(())
}

fn body(docs: &Docs) -> &str {
    docs.contents.as_deref().unwrap_or("").trim()
}

fn cell(docs: &Docs) -> String {
    body(docs).replace('|', "\\|").replace('\n', " ")
}

fn required(docs: &Docs, name: &str, missing: &mut Vec<String>) {
    if body(docs).is_empty() {
        missing.push(name.into());
    }
}

fn optional_type(resolve: &Resolve, value: Option<Type>) -> Result<String> {
    value
        .map(|t| type_name(resolve, t))
        .transpose()
        .map(|s| s.unwrap_or_else(|| "_".into()))
}

fn type_name(resolve: &Resolve, value: Type) -> Result<String> {
    Ok(match value {
        Type::Id(id) => {
            let def = &resolve.types[id];
            if let Some(name) = &def.name {
                name.clone()
            } else {
                kind_text(resolve, &def.kind)?
            }
        }
        Type::Bool => "bool".into(),
        Type::U8 => "u8".into(),
        Type::U16 => "u16".into(),
        Type::U32 => "u32".into(),
        Type::U64 => "u64".into(),
        Type::S8 => "s8".into(),
        Type::S16 => "s16".into(),
        Type::S32 => "s32".into(),
        Type::S64 => "s64".into(),
        Type::F32 => "f32".into(),
        Type::F64 => "f64".into(),
        Type::Char => "char".into(),
        Type::String => "string".into(),
        Type::ErrorContext => "error-context".into(),
    })
}

fn kind_text(resolve: &Resolve, kind: &TypeDefKind) -> Result<String> {
    Ok(match kind {
        TypeDefKind::Type(t) => type_name(resolve, *t)?,
        TypeDefKind::List(t) => format!("list<{}>", type_name(resolve, *t)?),
        TypeDefKind::Option(t) => format!("option<{}>", type_name(resolve, *t)?),
        TypeDefKind::Result(r) => format!(
            "result<{}, {}>",
            optional_type(resolve, r.ok)?,
            optional_type(resolve, r.err)?
        ),
        TypeDefKind::Tuple(t) => format!(
            "tuple<{}>",
            t.types
                .iter()
                .map(|t| type_name(resolve, *t))
                .collect::<Result<Vec<_>>>()?
                .join(", ")
        ),
        _ => bail!("unsupported WIT type in P0 generator: {kind:?}"),
    })
}
